const ShopActionTypes = {
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
  ADD_COLLECTIONS_START: "ADD_COLLECTIONS_START",
  ADD_COLLECTIONS_SUCCESS: "ADD_COLLECTIONS_SUCCESS",
  ADD_COLLECTIONS_FAILURE: "ADD_COLLECTIONS_FAILURE",
  UPDATE_COLLECTIONS_START: "UPDATE_COLLECTIONS_START",
  UPDATE_COLLECTIONS_SUCCESS: "UPDATE_COLLECTIONS_SUCCESS",
  UPDATE_COLLECTIONS_FAILURE: "UPDATE_COLLECTIONS_FAILURE",
  DELETE_COLLECTIONS_START: "DELETE_COLLECTIONS_START",
  DELETE_COLLECTIONS_SUCCESS: "DELETE_COLLECTIONS_SUCCESS",
  DELETE_COLLECTIONS_FAILURE: "DELETE_COLLECTIONS_FAILURE",
  ADD_CATEGORY_START: "ADD_CATEGORY_START",
};

export default ShopActionTypes;
