const ShopActionTypes = {
  LOADING_COLLECTION_ACTION: "LOADING_COLLECTION_ACTION",
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
  ADD_COLLECTIONS_START: "ADD_COLLECTIONS_START",
  ADD_COLLECTIONS_SUCCESS: "ADD_COLLECTIONS_SUCCESS",
  ADD_COLLECTIONS_FAILURE: "ADD_COLLECTIONS_FAILURE",
  EDIT_COLLECTIONS_START: "EDIT_COLLECTIONS_START",
  EDIT_COLLECTIONS_SUCCESS: "EDIT_COLLECTIONS_SUCCESS",
  EDIT_COLLECTIONS_FAILURE: "EDIT_COLLECTIONS_FAILURE",
  DELETE_COLLECTIONS_START: "DELETE_COLLECTIONS_START",
  DELETE_COLLECTIONS_SUCCESS: "DELETE_COLLECTIONS_SUCCESS",
  DELETE_COLLECTIONS_FAILURE: "DELETE_COLLECTIONS_FAILURE",
  ADD_CATEGORY_START: "ADD_CATEGORY_START",
  ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
  EDIT_CATEGORY_START: "EDIT_CATEGORY_START",
  EDIT_CATEGORY_SUCCESS: "EDIT_CATEGORY_SUCCESS",
  DELETE_CATEGORY_START: "DELETE_CATEGORY_START",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
  FETCH_COLLECTION_BY_ID_START: "FETCH_COLLECTION_BY_ID_START",
  FETCH_COLLECTION_BY_ID_SUCCESS: "FETCH_COLLECTION_BY_ID_SUCCESS",
  FETCH_COLLECTION_BY_ID_FAILURE: "FETCH_COLLECTION_BY_ID_FAILURE",
  FETCH_COLLECTION_BY_PRODUCT_ID_START: "FETCH_COLLECTION_BY_PRODUCT_ID_START",
  FETCH_COLLECTION_BY_PRODUCT_ID_SUCCESS:
    "FETCH_COLLECTION_BY_PRODUCT_ID_SUCCESS",
  FETCH_COLLECTION_BY_PRODUCT_ID_FAILURE:
    "FETCH_COLLECTION_BY_PRODUCT_ID_FAILURE",
  RESET_COLLECTION_BY_PRODUCT_ID: "RESET_COLLECTION_BY_PRODUCT_ID",
};

export default ShopActionTypes;
