const ShippingActionTypes = {
  FETCH_PROVINCE_START: "FETCH_PROVINCE_START",
  FETCH_PROVINCE_ERROR: "FETCH_PROVINCE_ERROR",
  FETCH_PROVINCE_SUCCESS: "FETCH_PROVINCE_SUCCESS",
  FETCH_CITY_START: "FETCH_CITY_START",
  FETCH_CITY_ERROR: "FETCH_CITY_ERROR",
  FETCH_CITY_SUCCESS: "FETCH_CITY_SUCCESS",
  FETCH_SHIPPING_COST_START: "FETCH_SHIPPING_COST_START",
  FETCH_SHIPPING_COST_ERROR: "FETCH_SHIPPING_COST_ERROR",
  FETCH_SHIPPING_COST_SUCCESS: "FETCH_SHIPPING_COST_SUCCESS",
};

export default ShippingActionTypes;
