const ModalActionTypes = {
  IS_OPEN_ADD_CATEGORY: "IS_OPEN_ADD_CATEGORY",
  IS_OPEN_EDIT_CATEGORY: "IS_OPEN_EDIT_CATEGORY",
  IS_OPEN_ADD_PRODUCT: "IS_OPEN_ADD_PRODUCT",
  IS_OPEN_EDIT_PRODUCT: "IS_OPEN_EDIT_PRODUCT",
  IS_OPEN_MODAL_UPLOAD_TRANSFER_PROOF: "IS_OPEN_MODAL_UPLOAD_TRANSFER_PROOF",
  IS_OPEN_MODAL_SERVICE_NUMBER: "IS_OPEN_MODAL_SERVICE_NUMBER",
  IS_OPEN_MODAL_ADD_ADDRESS: "IS_OPEN_MODAL_ADD_ADDRESS",
  IS_OPEN_MODAL_EDIT_ADDRESS: "IS_OPEN_MODAL_EDIT_ADDRESS",
};

export default ModalActionTypes;
