const ModalActionTypes = {
  IS_OPEN_ADD_CATEGORY: "IS_OPEN_ADD_CATEGORY",
  IS_OPEN_EDIT_CATEGORY: "IS_OPEN_EDIT_CATEGORY",
  IS_OPEN_ADD_PRODUCT: "IS_OPEN_ADD_PRODUCT",
  IS_OPEN_EDIT_PRODUCT: "IS_OPEN_EDIT_PRODUCT",
};

export default ModalActionTypes;
