const CheckoutActionTypes = {
  CHECKOUT_START: "CHECKOUT_START",
  CHECKOUT_SUCCESS: "CHECKOUT_SUCCESS",
  CHECKOUT_FAILURE: "CHECKOUT_FAILURE",
  FETCH_CHECKOUT_DATA_START: "FETCH_CHECKOUT_DATA_START",
  FETCH_CHECKOUT_DATA_SUCCESS: "FETCH_CHECKOUT_DATA_SUCCESS",
  FETCH_CHECKOUT_DATA_ERROR: "FETCH_CHECKOUT_DATA_ERROR",
  FETCH_CHECKOUT_DATA_BY_USER_ID_START: "FETCH_CHECKOUT_DATA_BY_USER_ID_START",
  FETCH_CHECKOUT_DATA_BY_USER_ID_SUCCESS:
    "FETCH_CHECKOUT_DATA_BY_USER_ID_SUCCESS",
  FETCH_CHECKOUT_DATA_BY_USER_ID_ERROR: "FETCH_CHECKOUT_DATA_BY_USER_ID_ERROR",
  UPLOAD_TRANSFER_PROOF_START: "UPLOAD_TRANSFER_PROOF_START",
  UPLOAD_TRANSFER_PROOF_SUCCESS: "UPLOAD_TRANSFER_PROOF_SUCCESS",
  UPLOAD_TRANSFER_PROOF_ERROR: "UPLOAD_TRANSFER_PROOF_ERROR",
  SUBMIT_SERVICE_NUMBER_START: "SUBMIT_SERVICE_NUMBER_START",
  SUBMIT_SERVICE_NUMBER_SUCCESS: "SUBMIT_SERVICE_NUMBER_SUCCESS",
  SUBMIT_SERVICE_NUMBER_ERROR: "SUBMIT_SERVICE_NUMBER_ERROR",
};

export default CheckoutActionTypes;
